steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - gcloud
      - services
      - enable
      - cloudfunctions.googleapis.com
      - cloudscheduler.googleapis.com
      - run.googleapis.com

  # Scheduler
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: bash
    args:
      - '-c'
      - |
        if ! gcloud scheduler jobs describe publish-job --location=$LOCATION > /dev/null 2>&1; then
          echo "Creating Cloud Scheduler job..."
          gcloud scheduler jobs create http publish-job \
            --schedule="*/59 23 28-31 * *" \
            --uri="https://$LOCATION-$PROJECT_ID.cloudfunctions.net/api/message" \
            --http-method=POST \
            --location=$LOCATION \
        else
          echo "Scheduler job already exists. Skipping."
        fi

  # Cloud function
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - gcloud
      - functions
      - deploy
      - api
      - '--region=$LOCATION'
      - '--source=.'
      - '--trigger-http' #the function can be accesed with the browser
      - '--runtime=nodejs20'
      - '--entry-point=apiNEST' #main function at src/main.ts
      - '--gen2' #specifying a 2nd gen function
      - '--allow-unauthenticated' #allowing public access
options:
  logging: CLOUD_LOGGING_ONLY
