steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        if ! gcloud pubsub topics describe demo-topic > /dev/null 2>&1; then
          echo "Creating topic: demo-topic"
          gcloud pubsub topics create demo-topic
        else
          echo "Topic demo-topic already exists. Skipping creation."
        fi

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:alpine'
    args:
      - gcloud
      - functions
      - deploy
      - api
      - '--region=asia-east1'
      - '--source=.'
      - '--trigger-http' #the function can be accesed with the browser
      - '--runtime=nodejs20'
      - '--entry-point=apiNEST' #main function at src/main.ts
      - '--gen2' #specifying a 2nd gen function
      - '--allow-unauthenticated' #allowing public access
options:
  logging: CLOUD_LOGGING_ONLY
